### ISSUE TITLE
Bug: After reloading neos-ui - ckstyles classes are missing

### ISSUE THREAD

**Issue by SimonPaidla** [techdivision/ckstyles#2]
Actual state: After setting classes from more than one dropdown and then reloading neos-ui, classes from any other than the last dropdown are missing.
Target state: Any class that has been set should remain set.
Configuration: Used default settings from Readme
Tested with neos-ui versions in different projects: 3.8.1, 4.0.0, 5.0.0
Reproduction: not consistently with every project; not clear, why. 
1) Add settings from Readme and add the Readme-styling for those classes
2) Add class "Red" to one portion of the text and "small" to another portion. 
3) publish 
4) The "red" class will be gone, but the "small" class should still be there. (They are visible during load process)
5) In frontend, both classes should be visible until next publish.

**Comment by masilikum** [comment]
The error seems to be caused by faulty example configuration: An empty class should not be used to reset the class, since the SelectBox contains an "x" button for resetting the current class.

After removing this configuration the backend rendering seemed to work fine.

The example configuration and documentation have been adjusted accordingly. 
#4
